package uz.pdp.springsecurity.enums;

public enum Employee {
    UPLOAD_MEDIA,
    DOWNLOAD_MEDIA,
    VIEW_MEDIA_INFO,
    DELETE_MEDIA,
    ADD_BRAND,
    EDIT_BRAND,
    VIEW_BRAND,
    DELETE_BRAND,
    ADD_CURRENCY,
    EDIT_CURRENCY,
    VIEW_CURRENCY,
    DELETE_CURRENCY,
    ADD_MEASUREMENT,
    EDIT_MEASUREMENT,
    VIEW_MEASUREMENT,
    DELETE_MEASUREMENT,

    ADD_TRADE,
    EDIT_TRADE,
    VIEW_MY_TRADE,
    DELETE_MY_TRADE,

    ADD_PAY_METHOD,
    EDIT_PAY_METHOD,
    VIEW_PAY_METHOD,
    DELETE_PAY_METHOD,
    ADD_PAY_STATUS,
    EDIT_PAY_STATUS,
    VIEW_PAY_STATUS,
    DELETE_PAY_STATUS,
}
