package uz.pdp.springsecurity.enums;

public enum Permissions {

    ADD_ADDRESS,
    EDIT_ADDRESS,
    VIEW_ADDRESS,
    DELETE_ADDRESS,

    UPLOAD_MEDIA,
    DOWNLOAD_MEDIA,
    VIEW_MEDIA_INFO,
    DELETE_MEDIA,

    ADD_BRANCH,
    EDIT_BRANCH,
    VIEW_BRANCH,
    DELETE_BRANCH,

    ADD_BRAND,
    EDIT_BRAND,
    VIEW_BRAND,
    DELETE_BRAND,

    ADD_CATEGORY,
    EDIT_CATEGORY,
    VIEW_CATEGORY,
    DELETE_CATEGORY,

    ADD_CURRENCY,
    EDIT_CURRENCY,
    VIEW_CURRENCY,
    DELETE_CURRENCY,

    ADD_CUSTOMER,
    EDIT_CUSTOMER,
    VIEW_CUSTOMER,
    DELETE_CUSTOMER,

    ADD_MEASUREMENT,
    EDIT_MEASUREMENT,
    VIEW_MEASUREMENT,
    DELETE_MEASUREMENT,

    ADD_OUTLAY,
    EDIT_OUTLAY,
    VIEW_OUTLAY,
    DELETE_OUTLAY,

    ADD_PRODUCT,
    EDIT_PRODUCT,
    VIEW_PRODUCT,
    DELETE_PRODUCT,

    ADD_ROLE,
    EDIT_ROLE,
    VIEW_ROLE,
    DELETE_ROLE,

    ADD_SUPPLIER,
    EDIT_SUPPLIER,
    VIEW_SUPPLIER,
    DELETE_SUPPLIER,

    ADD_USER,
    EDIT_USER,
    VIEW_USER,
    DELETE_USER,
    EDIT_MY_PROFILE,

    ADD_TRADE,
    EDIT_TRADE,
    VIEW_ALL_TRADE,
    VIEW_TRADE,
    DELETE_TRADE,
    VIEW_MY_TRADE,
    DELETE_MY_TRADE,

    ADD_PAY_METHOD,
    EDIT_PAY_METHOD,
    VIEW_PAY_METHOD,
    DELETE_PAY_METHOD,

    ADD_PAY_STATUS,
    EDIT_PAY_STATUS,
    VIEW_PAY_STATUS,
    DELETE_PAY_STATUS,

    ADD_PURCHASE,
    EDIT_PURCHASE,
    VIEW_PURCHASE,
    DELETE_PURCHASE,

    ADD_EXCHANGE,
    EDIT_EXCHANGE,
    VIEW_EXCHANGE,
    DELETE_EXCHANGE,

    VIEW_BENEFIT_AND_LOST,

    ADD_BUSINESS,
    EDIT_BUSINESS,
    VIEW_BUSINESS,
    DELETE_BUSINESS


}
