
###
POST http://localhost:8080/api/branch
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "name": "Farg'ona filial",
  "addressId": 1,
  "businessId": 1
}

###
POST http://localhost:8080/api/brand
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "name": "APPLE",
  "branchId": 3
}

###
POST http://localhost:8080/api/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "name": "Noutbook",
  "branchId": 1
}

###
POST http://localhost:8080/api/currency
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "name": "Dollar",
  "currentCourse": 10050,
  "branchId": 1
}

###
POST http://localhost:8080/api/customer
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "name": "Sardor3",
  "phoneNumber": "+998950041830",
  "telegram": "@sari3",
  "branchId": 3
}

###
POST http://localhost:8080/api/measurement
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "name": "Dona",
  "branchId": 3
}

###
POST http://localhost:8080/api/paymethod
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "type": "Uzs",
  "branchId": 1
}

###
POST http://localhost:8080/api/product
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "name": "Cori 3",
  "quantity": 1000,
  "barcode": 1111,
  "brandId": 2,
  "categoryId": 1,
  "measurementId": 1,
  "photoIds": [
    1,
    2
  ],
  "minQuantity": 10,
  "buyPrice": 100,
  "salePrice": 200,
  "tax": 20,
  "branchId": [
    4
  ],
  "expireDate": null,
  "dueDate": null
}

###
POST http://localhost:8080/api/role
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0Mjc0MDYxMiwiZXhwIjoxNjQyNzc2NjEyLCJyb2xlIjoiQWRtaW4ifQ.hcI1UUtxPAix4Q_ZX5NDRh_90ToGfTzL9QnuGnr1LmlVBYVCNSrRTh4Nt4rEaZwFvebt193SnlzTCG1gqrNrTw
Content-Type: application/json

{
  "name": "Kassir",
  "permissions": [
    "VIEW_ADDRESS",
    "VIEW_BRAND",
    "VIEW_CATEGORY",
    "VIEW_CURRENCY",
    "VIEW_CUSTOMER",
    "VIEW_MEASUREMENT",
    "VIEW_PRODUCT",
    "VIEW_OUTLAY"
  ],
  "description": "Hisobchi faqat malumotlarni ko'raoladi"
}

###
GET http://localhost:8080/api/role/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0Mjc0MDYxMiwiZXhwIjoxNjQyNzc2NjEyLCJyb2xlIjoiQWRtaW4ifQ.hcI1UUtxPAix4Q_ZX5NDRh_90ToGfTzL9QnuGnr1LmlVBYVCNSrRTh4Nt4rEaZwFvebt193SnlzTCG1gqrNrTw

###
POST http://localhost:8080/api/supplier
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw
Content-Type:application/json

{
  "name": "ali",
  "phoneNumber": "888888",
  "telegram": "dasdsdcsad",
  "supplierType": "Yetkazib beruvchi"
}
###
PUT http://localhost:8080/api/product/{{id}}

###
POST http://localhost:8080/api/purchase
Content-Type: application/json

{
  "dealerId": 1,
  "purchaseStatusId": 1,
  "paymentStatusId": 1,
  "branchId": 1,
  "date": "2022-01-17",
  "description": "evnqlerjvnlejnvlwejnv",
  "deliveryPrice": 50000,
  "purchaseProductsDto": [
    {
      "purchasedQuantity": 10,
      "productPurchaseId": 4
    },
    {
      "purchasedQuantity": 100,
      "productPurchaseId": 1
    }
  ]
}


###
POST http://localhost:8080/api/purchas

###
POST http://localhost:8080/api/exchange-product-brach
Content-Type: application/json

{
  "shippedBranchId": 1,
  "receivedBranchId": 2,
  "exchangeDate": "2020-07-18",
  "description": "dvsdvsdvsdv sadvsd vsadv sadvsad vs adv sd vs dav s dv s dv sd v sd v as dvsa dv asdv",
  "exchangeStatusId": 1,
  "exchangeProductDTOS": [
    {
      "exchangeProductQuantity": 50,
      "productExchangeId": 7
    }
  ]
}



###
GET http://localhost:8080/api/trade/get-pdf/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzI2MjAxNSwiZXhwIjoxNjQzMjk4MDE1LCJyb2xlIjoiQWRtaW4ifQ.wLSUegYuXMzW7N0L1XwpETdQZtFVUaJSlaRXOe6knFZt6BsO-JsvrprB5GzxaPk0Otctduka8r0D1QyvaosVUg

###
POST http://localhost:8080/api/auth/login

###
GET http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzI2NTA5MCwiZXhwIjoxNjQzMzAxMDkwLCJyb2xlIjoiQWRtaW4ifQ.aqw40fd6fk89alXsFdIibNjGb1euOMa5yl-QFppdCzdqDKVbmRiK_tCVwy1T5NJ-BehxGgdsqZKQTgV31_7ytA

###
POST http://localhost:8080/api/address
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw
Content-Type:application/json

{
  "city": "Farg'ona",
  "district": "Chilonzor",
  "street": "Mirobod",
  "home": "1"
}

###
POST http://localhost:8080/api/attachment/uploadAnyFile

###
POST http://localhost:8080/api/attachment/upload

###
POST http://localhost:8080/api/purchase
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw
Content-Type:application/json

{
  "dealerId": 1,
  "seller": 1,
  "purchaseStatusId": 1,
  "paymentStatusId": 1,
  "branchId": 1,
  "date": "2022-12-07",
  "description": "dvqervevv ev erv q evlkqnev qoekv oq vqe veqo ve rve rv ",
  "deliveryPrice": 4000,
  "purchaseProductsDto": [
    {
      "purchasedQuantity": 10,
      "productPurchaseId": 3
    },
    {
      "purchasedQuantity": 10,
      "productPurchaseId": 4
    },
    {
      "purchasedQuantity": 10,
      "productPurchaseId": 5
    },
    {
      "purchasedQuantity": 10,
      "productPurchaseId": 6
    }
  ]
}

###
GET http://localhost:8080/api/purchase/get-pdf/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw

###
GET http://localhost:8080/api/purchase/get-pdf/1


###
GET http://localhost:8080/api/purchase
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw

###
POST http://localhost:8080/api/benefit-lost
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw
Content-Type: application/json

{
  "firstDate": "2021-01-10",
  "secondDate": "2023-01-25",
  "branchId": 2
}

###
POST http://localhost:8080/api/outlay
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw
Content-Type: application/json

{
  "outlayCategoryId": 1,
  "totalSum": 80000,
  "branchId": 2,
  "spenderId": 1,
  "description": "asdjnqoifwoij wefiwheihqwofih qwefiwhefhweofhew wqhfeowhqefohiwqefihqw",
  "date": "2022-01-20"
}

###
POST http://localhost:8080/api/outlayCategory
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzM0Nzk3OSwiZXhwIjoxNjQzMzgzOTc5LCJyb2xlIjoiQWRtaW4ifQ.2czxcvpOMKWz4UUW6DuNpopWNYbOKkB7dZbTG8nB5FZo2sW1mLeHK0hpGHkChs6UwEPVFtp7q8oVvXRYrg_IQw
Content-Type: application/json

{
  "title": "Balo bormikin buni qo'shib"
}


###
POST http://localhost:8080/api/benefit-lost/one-date
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzYwNjk3MSwiZXhwIjoxNjQzNjQyOTcxLCJyb2xlIjoiQWRtaW4ifQ.aGPqshaG137_2G0sU23kR3sYTBUsKt-vsqunZd67I-XmctWqewN86sT6YrI0xiNCnWmQ9xQ_hkrVKpcgeiOiOA
Content-Type: application/json

{
  "firstDate": "2022-01-12",
  "secondDate": null,
  "branchId": 2
}

<> 2022-01-31T143021.409.json
<> 2022-01-31T143011.200.json
<> 2022-01-31T142934.409.json
<> 2022-01-31T142733.200.json
<> 2022-01-31T142318.500.json
<> 2022-01-31T142153.500.json
<> 2022-01-31T142018.500.json
<> 2022-01-31T141959.500.json
<> 2022-01-31T141814.409.json
<> 2022-01-31T141731.409.json
<> 2022-01-31T123447.409.json

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

<> 2022-02-01T111056.200.txt
<> 2022-02-01T100718.200.txt
<> 2022-02-01T100628.401.json


###

POST http://localhost:8080/api/auth/login

###
GET http://localhost:8080/api/address

###
GET http://localhost:8080/api/trade/get-by-PayDate/2022-01-19
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ

<> 2022-01-31T143820.200.json
<> 2022-01-31T143341.400.json

###
GET http://localhost:8080/api/trade/get-by-customerId/1

###
GET http://localhost:8080/api/role
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ

<> 2022-02-01T110449.200.json


###
POST http://localhost:8080/api/user
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0MzY5MjAzNywiZXhwIjoxNjQzNzI4MDM3LCJyb2xlIjoiQWRtaW4ifQ.sGMtvxWZkmOMx9wOwC3RsxpKs81Ni1m6mFavnOmoIjSzV_wlEO6_RJFF72-mbKKfh-IsbCXDfVmosK31eFDwHQ
Content-Type: application/json

{
  "firstName": "Ibrohimjon",
  "lastName": "Yursunov",
  "username": "ali",
  "password": "222",
  "roleId": 1,
  "branchId": 1,
  "businessId": 1,
  "enabled": true
}

<> 2022-02-01T101109.200.json

###
POST http://localhost:8080/api/trade
