###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

###

POST http://localhost:8080/api/branch
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "name": "Test 4  filial",
  "addressId": 1,
  "businessId": 1
}

<> 2022-02-08T153813.200.json
<> 2022-02-08T153806.200.json
<> 2022-02-08T141902.200.json
<> 2022-02-08T122115.200.json
<> 2022-02-08T120822.200.json

###
POST http://localhost:8080/api/brand
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "name": "ASUS",
  "businessId": 1
}

<> 2022-02-08T153726.200.json
<> 2022-02-08T151806.200.json
<> 2022-02-08T141906.200.json
<> 2022-02-08T122126.200.json
<> 2022-02-08T120831.200.json

###
POST http://localhost:8080/api/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "name": "Noutbook",
  "businessId": 1
}

<> 2022-02-08T153732.200.json
<> 2022-02-08T151756.200.json
<> 2022-02-08T141911.200.json
<> 2022-02-08T122129.200.json
<> 2022-02-08T120837.200.json

###
POST http://localhost:8080/api/currency
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "name": "Uzs",
  "currentCourse": 10050,
  "businessId": 1
}

<> 2022-02-08T153738.200.json
<> 2022-02-08T141915.200.json
<> 2022-02-08T122134.200.json
<> 2022-02-08T120842.200.json

###
POST http://localhost:8080/api/customer
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "name": "Sardor",
  "phoneNumber": "+998950041830",
  "telegram": "@sari",
  "businessId": 1
}

<> 2022-02-08T153752.200.json
<> 2022-02-08T151856.200.json
<> 2022-02-08T141919.200.json
<> 2022-02-08T122138.200.json
<> 2022-02-08T120846.200.json

###
POST http://localhost:8080/api/measurement
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "name": "Dona",
  "businessId": 1
}

<> 2022-02-08T153755.200.json
<> 2022-02-08T151901.200.json
<> 2022-02-08T141925.200.json
<> 2022-02-08T122141.200.json
<> 2022-02-08T120851.200.json

#
###
POST http://localhost:8080/api/product
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "name": "pepsi",
  "quantity": 5050,
  "barcode": 8252524,
  "brandId": 1,
  "categoryId": 1,
  "measurementId": 1,
  "photoIds": [
    1
  ],
  "minQuantity": 10,
  "buyPrice": 77,
  "salePrice": 777,
  "tax": 20,
  "branchId": [
   2
  ],
  "expireDate": null,
  "dueDate": null
}

###
POST http://localhost:8080/api/exchange-product-brach
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY0NDM4MTYwMywiZXhwIjoxNjQ0NDE3NjAzLCJyb2xlIjoiQWRtaW4ifQ.yIiyEbBc_fnyJlZIk5vF4OmN0-k5YZZDFVCQQxNtNtKIZ5Ejog5Bo_dI5b6RVHG5r5MZvHyOEvNI_4gMkPQNZg
Content-Type: application/json

{
  "shippedBranchId": 2,
  "receivedBranchId": 1,
  "exchangeDate": "2020-07-18",
  "description": "dvsdvsdvsdv sadvsd vsadv sadvsad vs adv sd vs dav s dv s dv sd v sd v as dvsa dv asdv",
  "exchangeStatusId": 1,
  "exchangeProductDTOS": [
    {
      "exchangeProductQuantity": 1,
      "productExchangeId": 13
    }
  ]
}
